-- AlterTable
ALTER TABLE "TravelPost" ADD COLUMN     "fromLat" DOUBLE PRECISION,
ADD COLUMN     "fromLng" DOUBLE PRECISION,
ADD COLUMN     "toLat" DOUBLE PRECISION,
ADD COLUMN     "toLng" DOUBLE PRECISION;
