ALTER TABLE "TravelPost" ADD COLUMN "pickupLat" DOUBLE PRECISION;
ALTER TABLE "TravelPost" ADD COLUMN "pickupLng" DOUBLE PRECISION;
ALTER TABLE "TravelPost" ADD COLUMN "dropLat" DOUBLE PRECISION;
ALTER TABLE "TravelPost" ADD COLUMN "dropLng" DOUBLE PRECISION;
ALTER TABLE "TravelPost" ADD COLUMN "distanceKm" DOUBLE PRECISION;
ALTER TABLE "TravelPost" ADD COLUMN "estimatedDuration" INTEGER;
